### ISSUE TITLE
Matrix size reduction in `hsaio_ecc_pkg`

### ISSUE THREAD

**Issue by zarubaf** [micprog/redundancy_cells#27]
Awesome stuff, thanks a lot for providing these useful implementations. I'd have one question regarding potentially reducing the complexity of the `hsiao_matrix` function since `verilator`/`fusion_compiler` seem to have some troubles to determining this efficiently :-D

In particular, I was wondering what the `MaxChoose` parameter in the `hsiao_ecc_pkg` must be. `MaxDataWidth`/`MaxParityWidth` is quite clear, but I was wondering whether we can also safely reduce `MaxChoose`? Maxium codeword size that we are encountering is 256-bit. Thanks!

**Comment by micprog** [comment]
The `MaxDataWidth`, `MaxParityWidth`, and `MaxChoose` parameters are only used for allocating sufficiently sized memory, as dynamic arrays do not work for synthesis tools or verilator (see #18 and a small part in #22). The computation of the matrices should not be affected by this, leading to the same result for each computation (maybe this can be cached in the tools somehow?).

The `MaxChoose` parameter originates from the number of possible combinations for choosing elements of a list, i.e., ${n \choose k}$, where $n$ is the number of code bits, and $k$ is odd and $\geq 3$. For this method, we select sufficient combinations for correction, i.e., the number of data bits. Therefore, to limit exactly to a minimal 256-bit data configuration, we can set the following parameters:
```systemverilog
localparam int unsigned MaxDataWidth = 256;
localparam int unsigned MaxParityWidth = 10;
localparam int unsigned MaxChoose = 252; // 10 choose 5
```
This way, the algorithm will look for 256 sets with ${10 \choose 3} =120$ to start, and will then pick a minimal set from the ${10 \choose 5}=252$ for the remaining necessary combinations.

Setting this up for the minimal configuration with 1024-bit data, `MaxChoose = 792` should suffice when limiting to 12 bits of parity, the slightly larger number was chosen for a bit more flexibility in the number of code bits.

I assume there is a more efficient and elegant way to construct this, especially as it ends up being static for the implementation, this was more or less taken directly from a software-based implementation to precompute a minimal matrix: https://github.com/lowRISC/opentitan/pull/20845
I assume iteratively recomputing the possible combinations, checking with the already chosen ones, may end up in a more memory-efficient implementation (completely removing the arrays with `MaxChoose`), however, computation time may increase. Feel free to propose a PR for this if you like!

**Comment by zarubaf** [comment]
Thanks a lot, @micprog! Those are great pointers, we'll try the different avenues to convince our tools :-) If okay I am closing the issue.
